### ISSUE TITLE
Task 7 rejected

### ISSUE THREAD

**Issue by e00dan** [terryboy/nervos-gitcoin#1]
Rejected because it's a copy of: https://github.com/assafom/dapp-nervos-integration

**Comment by terryboy** [comment]
Can I re-submit after making changes?

**Comment by terryboy** [comment]
> 拒绝，因为它是以下内容的副本：[https](https://github.com/assafom/dapp-nervos-integration) : [//github.com/assafom/dapp-nervos-integration](https://github.com/assafom/dapp-nervos-integration)
Sorry for my oversight, can I refer to the other modifications and submit again, thank you for your reply

**Comment by terryboy** [comment]
> 拒绝，因为它是以下内容的副本：[https](https://github.com/assafom/dapp-nervos-integration) : [//github.com/assafom/dapp-nervos-integration](https://github.com/assafom/dapp-nervos-integration)
Sorry for my oversight, can I refer to the other modifications and submit again, thank you for your reply

**Comment by CallmeOrange** [comment]
> Rejected because it's a copy of: https://github.com/assafom/dapp-nervos-integration

Sorry for my oversight, can I refer to the other modifications and submit again, thank you for your reply
